---
Name: liveticker
---

SilverStripe\Control\Director:
  rules:
    graphql-liveticker:
      Controller: 'SilverStripe\GraphQL\Controller'

SilverStripe\GraphQL\Controller:
  schema:
    types:
      livetickermessage: 'TheWebmen\Liveticker\GraphQL\LivetickerMessageTypeCreator'
    queries:
      readLivetickerMessages: 'TheWebmen\Liveticker\GraphQL\ReadLivetickerMessagesQueryCreator'
